apiVersion: v1
kind: Service
metadata:
  name: ibm-frontend-angular-service
spec:
  selector:
    app: ibm-frontend-angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
  # type: LoadBalancer
  # type: ClusterIP
